[build]
  Command = "npm run build"
  functions = "functions" #  netlify-lambda reads this
  publish = "./dist"

[dev]
  functionsSource = "./src/functions"
  publish = "./dist"
  functions = "functions"